# Generated by Django 3.2.6 on 2021-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0012_ingredientdata_recipesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientdata',
            name='ing_name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='recipe_category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
