# Generated by Django 3.2.6 on 2021-09-22 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0016_auto_20210922_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='fromMeasurementData',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='toMeasurementData',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
