# Generated by Django 3.2.6 on 2021-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0021_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategories',
            name='category_type',
            field=models.CharField(default='ingredient', max_length=225),
            preserve_default=False,
        ),
    ]
