# Generated by Django 3.2.6 on 2021-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0023_auto_20211006_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageareas',
            name='description',
            field=models.TextField(blank=True, max_length=225),
        ),
    ]
