# Generated by Django 3.2.6 on 2021-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0024_alter_storageareas_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_image', models.ImageField(blank=True, upload_to='ingredientimages')),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient_images',
            field=models.ManyToManyField(to='recipesandingredients.IngredientImages'),
        ),
    ]
