# Generated by Django 3.2.6 on 2021-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0026_nutritiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_images',
            field=models.ManyToManyField(blank=True, to='recipesandingredients.IngredientImages'),
        ),
    ]
