# Generated by Django 3.2.6 on 2021-10-15 12:36

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0030_nutritiondetails_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='preparation_instructions',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
