# Generated by Django 3.2.6 on 2021-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0034_auto_20211018_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsuppliers',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
