# Generated by Django 3.2.6 on 2021-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
