# Generated by Django 3.2.6 on 2021-09-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_usermodel_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('feeling', models.CharField(max_length=225)),
                ('suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
