# Generated by Django 3.2.6 on 2021-09-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredients',
            table='IngredientsTable',
        ),
    ]
