# Generated by Django 3.2.6 on 2021-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0004_alter_ingredients_qtyunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='suppliers',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
