# Generated by Django 3.2.6 on 2021-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0006_auto_20210902_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='hasMajorAllergens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='majorAllergens',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
