# Generated by Django 3.2.6 on 2021-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0007_auto_20210902_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='displayName',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
