# Generated by Django 3.2.6 on 2021-09-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0008_alter_ingredients_displayname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredients',
            table='Ingredients_Table',
        ),
    ]
