# Generated by Django 3.2.6 on 2021-09-08 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0010_auto_20210908_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='fromMeasurementData',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='toMeasurementData',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='toMeasurementUnits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None),
        ),
    ]
