# Generated by Django 3.2.6 on 2021-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0013_auto_20210915_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='recipe_user',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
