# Generated by Django 3.2.6 on 2021-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0014_recipesmodel_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='recipe_category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Labor', 'Labor'), ('Packaging', 'Packaging'), ('UnCategorized', 'UnCategorized')], max_length=225, null=True),
        ),
    ]
