# Generated by Django 3.2.6 on 2021-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0017_auto_20210922_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='company_name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='company_name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
