# Generated by Django 3.2.6 on 2021-09-30 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0020_auto_20210930_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('supplier_name', models.CharField(max_length=225)),
                ('order_email', models.EmailField(blank=True, max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sales_rep_first_name', models.CharField(blank=True, max_length=225)),
                ('sales_rep_last_name', models.CharField(blank=True, max_length=225)),
                ('sales_rep_email', models.EmailField(blank=True, max_length=225)),
                ('sales_rep_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('preferred_order_method', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Text', 'Text'), ('Online Portal', 'Online Portal'), ('Fax', 'Fax')], max_length=225)),
                ('delivery_days', models.CharField(blank=True, max_length=225)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
