# Generated by Django 3.2.6 on 2021-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0022_ingredientcategories_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='recipe_category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
