# Generated by Django 3.2.6 on 2021-10-11 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0025_auto_20211007_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('ingredient', models.CharField(max_length=225)),
                ('weight', models.FloatField(validators=[django.core.validators.RegexValidator(message='exmaple of valid weight be 240g or 240kg or 240lb', regex='\\d{1,9}(kg|lb)'), django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('total_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('saturated_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('trans_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('sodium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('total_carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('dietary_fiber', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('sugar', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_a', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_c', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('calcium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('iron', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_d', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('potassium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
            ],
        ),
    ]
