# Generated by Django 3.2.6 on 2021-10-12 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0027_alter_ingredients_ingredient_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiondetails',
            name='weight',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='exmaple of valid weight be 240g or 240kg or 240lb', regex='\\d{1,9}(kg|lb)'), django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')]),
        ),
    ]
