# Generated by Django 3.2.6 on 2021-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0036_auto_20211021_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='fdcId',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
