# Generated by Django 3.2.6 on 2021-11-01 12:05

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0037_ingredients_fdcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('production_plan_template', django_quill.fields.QuillField()),
            ],
        ),
    ]
