# Generated by Django 3.2.6 on 2021-11-01 13:52

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0038_productionplantemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=225)),
                ('target_yield', models.IntegerField()),
                ('category_batch', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('date_filed', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('template', django_quill.fields.QuillField(blank=True)),
                ('recipes', models.ManyToManyField(blank=True, to='recipesandingredients.Recipes')),
            ],
        ),
    ]
