# Generated by Django 3.2.6 on 2021-11-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesandingredients', '0039_productionplan_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionplan',
            old_name='date_filed',
            new_name='date_field',
        ),
    ]
