# Generated by Django 3.2.6 on 2021-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210927_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_country',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency_codes',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
